# Generated by Django 6.0.6 on 2026-06-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_create_at_student_dob_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=15, verbose_name='stu_name'),
        ),
    ]
