# Generated by Django 6.0.6 on 2026-06-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['Name'], 'verbose_name_plural': 'student'},
        ),
    ]
