# Generated by Django 6.0.6 on 2026-06-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['Name'], 'verbose_name': 'student', 'verbose_name_plural': 'student'},
        ),
        migrations.AlterModelTable(
            name='student',
            table='student_data',
        ),
    ]
