# Generated by Django 6.0.6 on 2026-07-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_patientmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_query', models.TextField()),
            ],
        ),
    ]
