# Generated by Django 6.0.6 on 2026-07-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_patientquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_city', models.CharField(max_length=50)),
                ('patient_mobil', models.IntegerField(max_length=50)),
                ('patient_password', models.CharField(max_length=50)),
            ],
        ),
    ]
