# Generated by Django 6.0.6 on 2026-07-24 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.RemoveField(
            model_name='patientquery',
            name='patient_email',
        ),
        migrations.RemoveField(
            model_name='patientquery',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='patientquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientquery',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='app.patientmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app.patient'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='app.department'),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_password',
            field=models.CharField(max_length=128),
        ),
    ]
