# Generated by Django 6.0.6 on 2026-07-24 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientquery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patientquery',
            name='patient',
        ),
        migrations.AddField(
            model_name='patientquery',
            name='patient_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientquery',
            name='patient_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department'),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_password',
            field=models.CharField(max_length=25),
        ),
    ]
