# Generated by Django 6.0.6 on 2026-07-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_patientmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientModel',
            new_name='PatientAppoint',
        ),
    ]
