# Generated by Django 6.0.6 on 2026-06-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Age', models.IntegerField(max_length=2)),
                ('Degignation', models.CharField(max_length=50)),
            ],
        ),
    ]
