# Generated by Django 6.0.6 on 2026-07-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='contact',
            field=models.IntegerField(max_length=11),
        ),
    ]
