# Generated by Django 6.0.6 on 2026-07-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_students_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='students',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
