# Generated by Django 6.0.7 on 2026-07-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField()),
                ('password', models.CharField()),
                ('confirm_password', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
