# Generated by Django 6.1 on 2026-08-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.PositiveIntegerField(max_length=10, null=True),
        ),
    ]
